version: "3.9"
services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "host"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - WEBUI_PORT=5080
    volumes:
      - ./config:/config
      - media_downloads:/downloads
    restart: unless-stopped

volumes:
  media_downloads:
    external: true
