version: "3.9"
name: media
services:
  # Stack 2 Specific
  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent:latest
    profiles: ["stack-2"]
    networks:
      - mynetwork
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - WEBUI_PORT=5080
    volumes:
      - qbittorrent:/config
      - downloads:/downloads
    ports:
      - 5080:5080
      - 6881:6881
      - 6881:6881/udp
    restart: "unless-stopped"
  
  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:latest
    profiles: ["stack-2"]
    networks:
      - mynetwork
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  # Stack 1 Specific
  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    profiles: ["stack-1"]
    networks:
      - mynetwork
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - jackett:/config
      - downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  transmission:
    container_name: transmission
    image: linuxserver/transmission:latest
    profiles: ["stack-1"]
    networks:
      - mynetwork
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - transmission:/config
      - downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  # Shared Services
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    profiles: ["stack-1", "stack-2"]
    networks:
      - mynetwork
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - radarr:/config
      - downloads:/downloads
    ports:
      - 7878:7878
    restart: "unless-stopped"

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    profiles: ["stack-1", "stack-2"]
    networks:
      - mynetwork
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - sonarr:/config
      - downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    profiles: ["stack-1", "stack-2"]
    networks:
      - mynetwork
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - bazarr:/config
    ports:
      - 6767:6767
    restart: unless-stopped

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    profiles: ["stack-1", "stack-2"]
    networks:
      - mynetwork
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - jellyseerr:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped

  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin:latest
    profiles: ["stack-1", "stack-2"]
    networks:
      - mynetwork
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - jellyfin:/config
      - downloads:/data
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 8920:8920
    restart: unless-stopped

volumes:
  downloads:
  qbittorrent:
  prowlarr:
  jackett:
  transmission:
  radarr:
  sonarr:
  bazarr:
  jellyseerr:
  jellyfin:

networks:
  mynetwork:
    external: true
