version: "3.9"
services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    network_mode: "host"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ./config:/config
      - media_downloads:/data
    restart: unless-stopped

volumes:
  media_downloads:
    external: true
