version: "3.9"
services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    network_mode: "host"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ./config:/config
      - media_downloads:/downloads
    restart: unless-stopped

volumes:
  media_downloads:
    external: true
